=== enatgvhh/hale-adv/src/ConfigAdv.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema erstellt mit XMLSpy v2019 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ConfigObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="logfile"/>
				<xs:element ref="gradleprojectpath"/>
				<xs:element ref="gmlloaderjarpath"/>
				<xs:element ref="fme"/>
				<xs:element ref="databaseconnection"/>
				<xs:element ref="member"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="database">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schema"/>
				<xs:element ref="table" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="databaseconnection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbname"/>
				<xs:element ref="user"/>
				<xs:element ref="host"/>
				<xs:element ref="port"/>
				<xs:element ref="password"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbname" type="xs:string"/>
	<xs:element name="fme">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fmepath"/>
				<xs:element ref="fmeworkbenchpath"/>
				<xs:element ref="fmeargs"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fmeargs" type="xs:string"/>
	<xs:element name="fmepath" type="xs:anyURI"/>
	<xs:element name="fmeworkbench" type="xs:string"/>
	<xs:element name="fmeworkbenchpath" type="xs:anyURI"/>
	<xs:element name="gmlloader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="javacommand" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="gmlloaderjarpath" type="xs:anyURI"/>
	<xs:element name="gradleprojectpath" type="xs:anyURI"/>
	<xs:element name="gradletask" type="xs:string"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="javacommand" type="xs:string"/>
	<xs:element name="logfile" type="xs:anyURI"/>
	<xs:element name="member">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gradletask" maxOccurs="unbounded"/>
				<xs:element ref="database"/>
				<xs:element ref="gmlloader"/>
				<xs:element ref="fmeworkbench"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="port" type="xs:short"/>
	<xs:element name="schema" type="xs:string"/>
	<xs:element name="table" type="xs:string"/>
	<xs:element name="user" type="xs:string"/>
</xs:schema>

=== enatgvhh/hale-adv/src/ConfigAdv.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConfigObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigAdv.xsd">
	<logfile>E:\logs\loggerAdv.log</logfile>
	<gradleprojectpath>E:\Program\gradle\inspire_alignements</gradleprojectpath>
	<gmlloaderjarpath>C:\inspire\GMLLoader</gmlloaderjarpath>
	<fme>
		<fmepath>C:\Program Files\FME</fmepath>
		<fmeworkbenchpath>E:\Program\FME\Workspaces\INSPIRE_adv</fmeworkbenchpath>
		<fmeargs>--SourceDataset_POSTGIS inspire_sourc --DestDataset_POSTGIS inspire_dest</fmeargs>
	</fme>
	<databaseconnection>
		<dbname>test</dbname>
		<user>tester</user>
		<host>localhost</host>
		<port>5432</port>
		<password>tester</password>
	</databaseconnection>
	<member>
		<gradletask>transform-tn-w-basis-dlm</gradletask>
		<gradletask>transform-tn-ra-basis-dlm</gradletask>
		<gradletask>transform-tn-a-basis-dlm</gradletask>
		<gradletask>transform-tn-ro-basis-dlm</gradletask>
		<database>
			<schema>tn_atkis</schema>
			<table>tn_atkis.gml_objects</table>
			<table>tn_atkis.wms_net_network</table>
			<table>tn_atkis.wms_tn_a_aerodromearea</table>
			<table>tn_atkis.wms_tn_a_apronarea</table>
			<table>tn_atkis.wms_tn_a_runwayarea</table>
			<table>tn_atkis.wms_tn_a_taxiwayarea</table>
			<table>tn_atkis.wms_tn_ra_railwayarea</table>
			<table>tn_atkis.wms_tn_ra_railwaylink</table>
			<table>tn_atkis.wms_tn_ra_railwaystationarea</table>
			<table>tn_atkis.wms_tn_ro_roadarea</table>
			<table>tn_atkis.wms_tn_ro_roadlink</table>
			<table>tn_atkis.wms_tn_ro_roadservicearea</table>
			<table>tn_atkis.wms_tn_w_waterwaylink</table>
			<table>tn_atkis.wms_tn_w_portarea</table>
			<table>tn_atkis.wms_tn_w_ferrycrossing</table>
			<table>tn_atkis.wms_tn_transportnetwork</table>
		</database>
		<gmlloader>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-ra-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=tn/datasource_tn_atkis_blob -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-w-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=tn/datasource_tn_atkis_blob -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>		
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-a-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=tn/datasource_tn_atkis_blob -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-ro-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=tn/datasource_tn_atkis_blob -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>			
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-ra-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=datasource_tn_atkis_4wms  -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-w-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=datasource_tn_atkis_4wms  -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-a-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=datasource_tn_atkis_4wms  -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
			<javacommand>java -Dhttp.proxyHost=111.11.111.111 -Dhttp.proxyPort=80 -jar deegree-gml-tool-1.1-dev.jar GmlLoader -pathToFile=E:\Program\gradle\inspire_alignements\transformiert\tn-ro-basis-dlm\result.gml -workspaceName=inspire -sqlFeatureStoreId=datasource_tn_atkis_4wms  -disabledResources=https://registry.gdi-de.org,http://inspire.ec.europa.eu</javacommand>
		</gmlloader>
		<fmeworkbench>transfer-tn-dlm.fmw</fmeworkbench>
	</member>
</ConfigObject>
